# Generated by Django 3.2.6 on 2021-08-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='body',
            name='plot_by_default',
            field=models.BooleanField(default=True),
        ),
    ]
